### ISSUE TITLE
bcrypt_sha256_file.ahk always outputs the same hash

### ISSUE THREAD

**Issue by Leemonn** [jNizM/AHK_CNG#3]
Hello, as title says I've been using this ahk script for long time but now I noticed it always outputs the same hash for a file I'm using for testing purposes, this file has a size of 4,5mb (I think that might be the problem). I'm using w10 version.
This problem doesn't occur when using https://github.com/jNizM/HashCalc/blob/master/src/HashCalc.ahk

**Comment by Leemonn** [comment]
Tested with W7 version (using w10 computer) and it works as expected. There is a problem with w10 version.

**Comment by Leemonn** [comment]
nvm, it was a weird bug caused by resource hacker. It added duplicated resources and that made w10 hash function always return the same value. For some reason this didn't happen on w7 version.

**Comment by jNizM** [comment]
Since BCryptHash performs a single hash computation, it will consume the full memory for string and file hashes. So if the file is 4 GB, the ram usage will be also 4 gb for the hash calculation. Its also slower than the other one and not compatible on windows 7.
Thats why I decided to remove the "win10" part.
